out_dir: data/unused_index_eval
strategy: balanced
split: test
seed: 44
shuffle: false

tasks:
  - task_id: si_ring
    task_type: single_index
    properties: [ring_index]
    candidate_multiplier: 6
    filters:
      max_smiles_length: 90
      max_answer_list_length: 10

  - task_id: si_aromatic_ring
    task_type: single_index
    properties: [aromatic_ring_index]
    candidate_multiplier: 6
    filters:
      max_smiles_length: 90
      max_answer_list_length: 10

  - task_id: si_carbon_atom
    task_type: single_index
    properties: [carbon_atom_index]
    candidate_multiplier: 8
    filters:
      max_smiles_length: 70
      max_answer_list_length: 18

  - task_id: si_hetero_atom
    task_type: single_index
    properties: [hetero_atom_index]
    candidate_multiplier: 6
    filters:
      max_smiles_length: 90
      max_answer_list_length: 10

  - task_id: mi_ring_aromatic
    task_type: multi_index
    properties: [ring_index, aromatic_ring_index]
    candidate_multiplier: 6
    filters:
      max_smiles_length: 90
      max_answer_list_length: 10

